spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ks?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 200312Zwx
mybatis-plus:
  configuration:
    # \u65E5\u5FD7
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #\u9A7C\u5CF0
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
